// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:93568806-641d-45aa-a27b-9ecd627d4dbd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qjvtPrQ4n",
    "aws_user_pools_web_client_id": "2tq1l391qtbish6iqpsjitrvff",
    "aws_appsync_graphqlEndpoint": "https://tlvbowtmt5ddjfk4cx7twhiwu4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3ewkmbjt25dzhiqlqdbrlmgoam"
};


export default awsmobile;
