// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c296b81c-75ce-4c5f-a598-dae763e409e7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7gcK8uXwm",
    "aws_user_pools_web_client_id": "1p8lqkabfk45tv73s80d51feuu",
    "aws_appsync_graphqlEndpoint": "https://wje7256rfvfe5orvnoz5oby2fi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jtxmz2wv5vaulb53fk77qe3xum",
    "aws_cloud_logic_custom": [
        {
            "name": "alogapi",
            "endpoint": "https://zd3umki0ck.execute-api.us-east-2.amazonaws.com/Prod",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
